# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['src/smartql/cli.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'smartql',
        'smartql.core',
        'smartql.cli',
        'smartql.database',
        'smartql.generator',
        'smartql.llm',
        'smartql.schema',
        'smartql.security',
        'smartql.result',
        'smartql.cache',
        'smartql.exceptions',
        'litellm',
        'sqlglot',
        'sqlalchemy',
        'pymysql',
        'pydantic',
        'click',
        'rich',
        'prompt_toolkit',
        'yaml',
        'httpx',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='smartql',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
